#:schema node_modules/wrangler/config-schema.json
name = "winsestar"
compatibility_date = "2024-03-01"
pages_build_output_dir = "."

[observability]
enabled = true

[[kv_namespaces]]
binding = "SVRGN_DB"
id = "7d23d163a70f458fa1e07212f05855fb"
